# Generated by Django 6.0 on 2026-02-12 18:19

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region='IR', unique=True, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Active'), (3, 'Banned')], default=2),
        ),
    ]
