# Generated by Django 6.0 on 2026-02-15 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=40)),
                ('model', models.CharField(max_length=60)),
                ('trim', models.CharField(blank=True, default='', max_length=80)),
                ('year', models.PositiveSmallIntegerField(max_length=4)),
                ('mileage_km', models.PositiveIntegerField()),
                ('fuel', models.IntegerField(choices=[(1, 'Gasoline'), (2, 'Diesel'), (3, 'Hybrid'), (4, 'Electric'), (5, 'CNG')], db_index=True)),
                ('gearbox', models.IntegerField(choices=[(1, 'Manual'), (2, 'Automatic')])),
                ('color', models.CharField(blank=True, default='', max_length=30)),
                ('body_style', models.CharField(blank=True, default='', max_length=30)),
                ('price', models.BigIntegerField(default=0)),
                ('is_price_negotiable', models.BooleanField(default=True)),
                ('city', models.CharField(max_length=50)),
                ('area', models.CharField(blank=True, default='', max_length=80)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.IntegerField(choices=[(1, 'Draft'), (2, 'Published'), (3, 'Sold'), (4, 'Archived')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listings/images/')),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listing.listing')),
            ],
        ),
        migrations.CreateModel(
            name='ListingPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='listing.listing')),
            ],
        ),
    ]
