# Generated by Django 6.0 on 2026-02-15 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_alter_listing_fuel_alter_listing_year_listingview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='make',
        ),
    ]
