# Generated by Django 6.0 on 2026-02-15 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_remove_listing_make'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='brand',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
